checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 1800
        runs: 1

    # Runs PHP CodeSniffer
    php_code_sniffer: true

     # PHP Mess Detector (http://phpmd.org)
    php_mess_detector: true

    # Security Advisory Checker
    sensiolabs_security_checker: true

    # Analyzes the size and structure of a PHP project
    php_pdepend: true

    # Analyzes the size and structure of a PHP project
    php_loc: true

    # Copy/Paste Detector
    php_cpd: true

    # Runs Scrutinizer's PHP Analyzer Tool
    php_analyzer: true

filter:
    # Folders we want to exclude
    excluded_paths: [_tests, _tools]
