language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - DB=mysql

before_install:
  - composer self-update

install:
  # Make sure all dev dependencies are installed
  - composer --working-dir=_protected/vendor install

before_script:
  # Set up databases for testing
  - mysql -e 'create database ph7cms_test;'
  - mysql ph7cms_test < _install/data/sql/MySQL/pH7_SchemaGame.sql
  - mysql ph7cms_test < _install/data/sql/MySQL/pH7_DataGame.sql
  - mysql ph7cms_test < _install/data/sql/MySQL/pH7_Core.sql

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
